# -*- coding: utf-8 -*-
"""RID155811_Desafio06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pw5KBrNaBI7M75tH5XCQMO2tl27r-KsZ

# Desafio 06: Organizando e analisando dados de um Airbnb
*link do Desafio: https://dncgroupbr.notion.site/Desafio-Organizando-e-analisando-dados-de-um-Airbnb-1c81b4d4252c8063a5e8cc402d69dab4


**Tarefas a serem executadas**


1.   Importação correta dos arquivos com pandas, verificação das primeiras linhas, tipos de dados e aplicação correta do merge entre os DataFrames.

2.   Identificação dos valores nulos com isnull().sum() e aplicação adequada de preenchimento com média ou moda. Uso criterioso do dropna() quando necessário.
    
3.   Visualização com boxplot e uso correto do método do IQR para definir limites e remover valores extremos de forma consistente.

4.   Conversão de variáveis categóricas com .astype('category').cat.codes. Interpretação clara dos códigos gerados e, opcionalmente, uso de mapeamento para facilitar a leitura.

##Importando bibliotecas e dados
"""

#installing the most recently version od pandas profiling
!pip install ydata-profiling

#used for data manipulation and metrics
import numpy as np
import pandas as pd
import calendar
from ydata_profiling import ProfileReport
from datetime import datetime

#graphic visualization of the data
import seaborn as sns
import matplotlib.pyplot as plt

#
from sklearn import metrics
from sklearn.preprocessing import scale, StandardScaler, OneHotEncoder, OrdinalEncoder

#Review
urlReview = 'https://drive.google.com/file/d/1UMiA1XboPvBeP415GOoxRIIV_wMY40VJ/view?usp=sharing'
urlReview = 'https://drive.google.com/uc?id=' + urlReview.split('/')[-2]
dfReview = pd.read_csv(urlReview, encoding='unicode_escape')

#Listings
urlListings = 'https://drive.google.com/file/d/1ZXLikeMG5pOfLse3miUAz3K_c36O_J1j/view?usp=sharing'
urlListings = 'https://drive.google.com/uc?id=' + urlListings.split('/')[-2]
dfListings = pd.read_csv(urlListings, encoding='unicode_escape')

"""## 1 - Leia o arquivo e inspecione os dados ##"""

#Review head
dfReview.head()

#Review info
dfReview.info()

#Listings head
dfListings.head()

#Listings info
dfListings.info()

#Rename Column
dfListings.rename(columns={'id':'listings_id'})

"""###Merge dos dados"""

dfAir = dfListings.merge(right=dfReview, on="id", how="left")

dfAir.info()

#ProfileReport(df)

"""## 2 - Limpeza e Tratamento de Dados ##"""

dfAir.isnull().sum()

dfAir.info()

#Filling NaN numbers with Avg Values
cols = ['bathrooms','bedrooms','beds','price','number_of_reviews','review_scores_rating']
dfAir[cols] = dfAir[cols].fillna(dfAir[cols].mean())

dfAir.isnull().sum()

"""## 3 - Visualização com boxplot e uso correto do método do IQR para definir limites e remover valores extremos de forma consistente. ##"""

#boxplot to import data, for me it's price and accommodates
dfAir['price'].plot(kind='box')

#boxplot to import data, for me it's price and accommodates
dfAir['accommodates'].plot(kind='box')

"""IQR = Q3 - Q1 : Interquartile Range

Limite Inferior = Q1 - 1.5 * IQR

Limite Superior = Q3 +1.5 * IQR
"""

dfPrice = dfAir['price']
dfAccommodates = dfAir['accommodates']

Q1p = dfPrice.quantile(0.25)
Q1a = dfAccommodates.quantile(0.25)
Q3p = dfPrice.quantile(0.75)
Q3a = dfAccommodates.quantile(0.75)
print(Q1p)

IQRprice = Q3p - Q1p
IQRaccommodates = Q3a - Q1a
print('IQR price:', IQRprice,'IQR Accommodates', IQRaccommodates)

limite_superiorPrice = Q3p + 1.5 * IQRprice
limite_inferiorPrice = Q1p - 1.5 * IQRprice
print('Limite Superior = ',limite_superiorPrice, ',Limite Inferior = ',limite_inferiorPrice)

#As the minor value was negative, we will use 0
dfAirIQR = dfAir[(dfAir['price']<limite_superiorPrice)]

dfAirIQR.info()

dfAirIQR['price'].plot(kind='box');

"""## 4 - Transformando Dados Categóricos ##


"""

dfAirIQR.info()

dfAirIQR['room_type'] = dfAirIQR['room_type'].astype('category').cat.codes
dfAirIQR.head()

dfAirIQR.info()

dfAirIQR.describe()

dfAirIQR.columns